services:
  nginx:
    volumes:
        - ${HOME}/data/wordpress_static:/usr/share
    build: ./nginx_image
    ports:
        - "443:443"
    depends_on:
        - php
    networks:
      - 42net

  php:
    volumes:
        - ${HOME}/data/wordpress_static:/usr/share
    build: ./php_image
    depends_on:
        - mariadb
    networks:
      - 42net

  mariadb:
    volumes:
        - ${HOME}/data/wordpress_db:/var/lib/mysql
    build:
        context: ./mariadb_image
        args:
            - DB_ROOT_USERPASS=${DB_ROOT_USERPASS}
            - DB_WORDPRESS_NAME=${DB_WORDPRESS_NAME}
            - DB_WORDPRESS_USERNAME=${DB_WORDPRESS_USERNAME}
            - DB_WORDPRESS_USERPASS=${DB_WORDPRESS_USERPASS}
    networks:
      - 42net

networks:
    42net:
