services:
  nginx:
    build: ./nginx_image
    ports:
        - "443:443"
    volumes:
        - static_files:/usr/share
    links:
        - "php:php"
    depends_on:
        - php

  php:
    build: ./php_image
    volumes:
        - static_files:/usr/share

volumes:
    static_files: {}
