services:
  nginx:
    build: ./nginx_image
    ports:
        - "443:443"
    volumes:
        - wordpress_static:/usr/share
    links:
        - "php:php"
    depends_on:
        - php

  php:
    build: ./php_image
    volumes:
        - wordpress_static:/usr/share
    links:
        - "mariadb:mariadb"
    depends_on:
        - mariadb

  mariadb:
    build:
        context: mariadb_image
        args:
            - DB_ROOT_USERPASS=${DB_ROOT_USERPASS}
            - DB_WORDPRESS_NAME=${DB_WORDPRESS_NAME}
            - DB_WORDPRESS_USERNAME=${DB_WORDPRESS_USERNAME}
            - DB_WORDPRESS_USERPASS=${DB_WORDPRESS_USERPASS}
    volumes:
        - wordpress_db:/var/lib/mysql

volumes:
    wordpress_static: {}
    wordpress_db: {}
